name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions  ~@
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo " ~I The job was automatically triggered by a{{{{ github.even>
      - run: echo " M-' This job is now running on {{${{ runner.}} }} server ho>
      - run: echo " ~N The name of your branch is{{{{ github.re}}}} and your re>
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo " M-! Th{{${{ github.reposito}} }} repository has been cloned>
      - run: echo " M-%️ The workflow is now ready to test your code on the runne
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo " ~O This job's status is{{{{ job.statu}}}}."


